FROM maven:3.5.2-alpine
#RUN rm -rf /usr/src/java-code
WORKDIR /usr/src/java-code
COPY . /usr/src/java-code/
RUN mvn package

WORKDIR /usr/src/java-app
RUN cp /usr/src/java-code/clients/target/*exec.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
